name: arcata

services:

  arcata:
    image: ghcr.io/imatpot/arcata:latest
    build: . # Use this if you cloned the repo and want to build it locally

    hostname: arcata
    container_name: arcata
    restart: unless-stopped

    network_mode: host # Alternatively, manually forward your server ports; I personally like UPnP.

    # Required if using network_mode: host and a hostname, otherwise FQDN lookup fails in TigerVNC.
    extra_hosts:
      - arcata:127.0.0.1

    environment:
      TZ: Europe/Zurich
      AUTO_ACCEPT_EULA: ${AUTO_ACCEPT_EULA:-0} # Please check README.md
      VNC_PASSWORD: ${VNC_PASSWORD:-lunaro}
      VNC_PORT: ${VNC_PORT:-5900}

    volumes:
      # Create these two on the host before the first start.
      - ./data/proton/prefix:/home/tenno/.wine/pfx:U
      - ./data/proton/cache:/home/tenno/.local/share/Steam/compatibilitytools.d:U
      - ./arcata.yaml:/opt/arcata/arcata.yaml:ro

