#!/usr/bin/env bash

# Openbox is a very small window manager.
# Running it leaves the display alive for VNC and also allows us to interact properly with the windows, e.g. to press 'Q' to gracefuly shut down.
exec openbox

